class NotExistsException(Exception):
    pass
    

class AlreadyExistsException(Exception):
    pass
    
